name: main test pipeline

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Run tests
        run: mvn verify -Dheadless=true
      - name: Publish html report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: ./target/cucumber-reports/*